
  
  window.webSnake = {};

  window.webSnake.urlMap = [
  {
    "oldUrl": "https://www.google.com/xjs/_/js/k=xjs.s.en.1gGYAjfJB_o.2019.O/ck=xjs.s._FEqZKugoRo.L.B1.O/am=AAAIAAAAAAAQAAAAAAAAAAAAAAgQQAQAAAAAAAAAAAAAAAAAAEAIAAQAAEAAAAAAAAAAAAAAAAAAIAAQAAAAAAAEAABDAAAAABgAAACBEAABgBIAIAAAEKIBIgAAAQAAAAAAAAAKPQAEAGAAAAAAAADgARgAjgAAAAAAAAABAAAACEAggACQAAAAAAAAAAAIAgAAAAAAAgAAAAQAAAAGABAAQACUAAAAACoAAAAACAAAAAAIAAAAAAAAAAAARBABAABEIAACAADA3-YbAAAeAAAAAABwAAAAAAAAAAACAAAAAAAAAAAAAABIBA4AAAAAAADCwAIAAAACAwAACAABARAAAAAAAAAAABAJkAAACAAAAADAAAAAAAAAAAAAAQCCEAgAgAAoAAEBAAABgIMHAAgAAAAAAAAAAAAKAAAAAAAACAAAAAAEACAIQAggAAAAAACAAAAAAAUgAAAAACAOAAAAAAAAACCQAkAAAgAYQQIAIFEQCCACAEAABDAAAAAQAQAAAAAAABASPwAIgAAAAAAAAEQAAAAAAACABEAAAAAAgAUAWCAEADAAAAAAcgA8HgBDBAUAAAAAAAAAAAAAAAAAAAAAAAAAAARAAcyBpCAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAACQIjwFAAAAAADA1gCA/d=0/dg=0/br=1/ujg=1/rs=ACT90oHptmHWwb0godGSeROxuX0iwS-Qvg/cb=loaded_h_0/m=syk3,aLUfP,wQlYve,sy9pf,sy4mn,sy4pr,sy9pe,sy9pd,sy5ud,sy30z,sy32x,sy30k,sy9w,sy30l,sy1qz,pKhWu,sy5t9,sy2n4,sy27t,oQfbDd,abd,sy5t3,TDFkye,sy8m2,sy8pk,sy8pi,sy8m5,sy4ha,sy5rm,sy4gr,syjd,sy9l,sy5rl,sy4gq,sy2q5,sy272,sy5rj,syia,sy8m3,sy8m4,sy1n0,sy1m3,sy1lp,sy1lo,sy1lf,sy1lr,sy1ln,sy1lq,sy1ly,sy4gd,sy4ge,sy1ll,sy1lm,sy8pj,sy5zt,qmjr3,sy8pg,sy5up,IQw9J,sy5t4,sy39o,sy177,sy39r,sy39p,sy53s,sy20o,sy53n,sy53q,sy20p,sy53o,sy39q,sy53p,sy53k,sy53j,sy53l,sy1r8,sy53m,sy27z,sy27x,sy3ym,sy27y,sy282,sy285,sy27v,sylq,sylr,sy27w,sy1rn,sy281,sym0,sy3yj,sy3b6,sy1s6,sy15b,sy15c,sy157,sy15d,sy53h,ily0Be,sy64g,sy3wn,Zihehd,sy60u,sy15i,sy3md,mf2ifc,sy311,sy310,n7qy6d,sy313,HPGtmd,sy2hw,sy316,sy314,sy169,syvo,syvb,syv8,syv7,syup,syuo,syru,sy30b,uLYJpc?cb=121509378&xjs=s3",
    "newUrl": "snake.js"
  }
];
  
  window.webSnake.blockedUrls = [
  "https://www.google.com/xjs/_/js/k=xjs.s.en.1gGYAjfJB_o.2019.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEAABABIAIAAAAAIAAAAAAAAAAAAAAAAACAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEAAgACQAAAAAAAAAAAIAgAAAAAAAgAAAAAAAAAGABAAQACEAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAQBAAAABEIAACAADA3-YbAAAaAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAABIAAAAAAAAAAAAwAIAAAACAwAACAABARAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAoAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAACAAAAAAAUAAAAAAAAOAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAABDAAAAAAAAAAAAAAAAACPwAIgAAAAAAAAAQAAAAAAAAABEAAAAAAAAAAQAAEADAAAAAAcgA8HgBDBAUAAAAAAAAAAAAAAAAAAAAAAAAAAARAAcyBJCAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAACQIjwFAAAAAADA1gCA/dg=0/ichc=1/rs=ACT90oEofofHF42UI7JaTooPoddXe-FC4g/cb=loaded_h_0?cb=121509378"
];
  
