
  
  window.webSnake = {};

  window.webSnake.urlMap = [
  {
    "oldUrl": "https://www.google.com/xjs/_/js/k=xjs.s.en.-pnnDAjjICQ.2019.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAiAAgAQACAAAQAAAAAAAAAAAAAAAAAAAAwABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQgAAAAZAAAAAAAAAAABAEAAAAAAACAAAAAAAAAAYAEABAACEAAAAACgAAAAAAAAAAAAAAAAAAAAAAABAEAAAAEQggAAAA_G2-AQBAAwAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAEgAAAAAAAAAAADAAgAAAAIDAAAEgIAACAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAACAAAAAAACgAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAQAAAAIACAAAAAABwAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAACAAAYAAAAAAAAAAAAAAACBHwAEQAAAAAAAAAQAAAAAAAAgAAIAAAAAAAAAAgABAAwAAACAHACPB8AQQQEAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAHMgCQiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACkCE8BAAAAAACwNQAg/dg=0/ichc=1/rs=ACT90oF4ztWyH4yvJBeT26SaE-xokHJmjQ/cb=loaded_h_0?cb=121509378",
    "newUrl": "snake.js"
  }
];
  
  window.webSnake.blockedUrls = [
  "https://www.googleapis.com/language/translate/v2"
];
  
